<?php

const VETERINARIO = "VETERINARIO";
const VET_ID = "VET_ID";
const VET_NOMBRE = "VET_NOMBRE";
const VET_EMAIL = "VET_EMAIL";
const VET_TELEFONO = "VET_TELEFONO";
const VET_ESPECIALIDAD = "VET_ESPECIALIDAD";
